# Generated by Django 4.2 on 2023-04-14 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UNDERWATERCAMERA', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Camera_Auto',
            new_name='Auto_cam',
        ),
    ]
