# Generated by Django 4.2 on 2023-04-15 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UNDERWATERCAMERA', '0002_rename_camera_auto_auto_cam'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto_cam',
            name='Check_cap',
            field=models.BooleanField(default=False),
        ),
    ]
