# Generated by Django 4.2 on 2023-04-16 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UNDERWATERCAMERA', '0003_auto_cam_check_cap'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auto_cam',
            options={},
        ),
        migrations.RemoveField(
            model_name='auto_cam',
            name='start_Time',
        ),
        migrations.AddField(
            model_name='auto_cam',
            name='start_time',
            field=models.TimeField(default='12:00'),
        ),
    ]
