# Generated by Django 4.2 on 2023-04-16 08:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UNDERWATERCAMERA', '0004_alter_auto_cam_options_remove_auto_cam_start_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auto_cam',
            name='start_time',
        ),
        migrations.AddField(
            model_name='auto_cam',
            name='start_Time',
            field=models.TimeField(default=datetime.time(8, 4, 53, 442107)),
        ),
    ]
