# Generated by Django 4.2 on 2023-04-16 08:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UNDERWATERCAMERA', '0005_remove_auto_cam_start_time_auto_cam_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto_cam',
            name='start_Time',
            field=models.TimeField(default=datetime.time(8, 11, 48, 805181)),
        ),
    ]
